sudo: required
language: bash
services:
- docker
env:
  matrix:
  - SNAPCASTVERSION=0.11.1
  global:
    - TRAVISCI_SCRIPT_DIR=/tmp/ci_scripts
    - DOCKER_USERNAME=nolte
    - secure: "dtw1YjVr/ZW9c1ErLz04rh8v+IojBO4k3JL+yM3H0fyIWc06xq5DPIgDuMMuqAknUJCpDu1WhC9lwqXWDoPNZqSQBVJs7ozYiHFpaoA5tTmUiGZ1MxB0ET2OGIWreSUSXYU9Z5Cf5aB5AsK3NXas3+3fiIaw6Lg9vLLF3c+AD9N2Qrby5ssgBzJ+tC2Wikrg8FHhHRXObxxb50Zhaj2AZlnemIt0yAutmGKAGdGPdJnNYppSOKdd3F08YtzPDWrxpqUJqFxRc7k11Q6XJoSFWSmqKYEDB1RIC421ZRCSsDfR5nYkGRT2jcqXLGUnE9DLTyXjB1tMDYApw8cY9wXZeb/CowffHdus8laO/fIkMu2mA/faeM30F65IToKkHjRD3LcaDGU3KM+xGbqe+ySx+IJ59DtDXHNVS1E/bRu8A6/adulMd07PCgLFBnxsn88aquaDGdw7awFzqGmuEdirJivj5AQDJ8nYUPJGu/ifZ3YyFCwvbN3MgU3fSq6KO7wR78bGe2AdwZFvbePuG952mQ0V07f5V6iJV4Sl1Kc0VUeV/jdbtxtR6kZYezXTm64SgQ882RMjdT7Q55Bw1ICivQVGOABlGl0pRzK7YlgHpPnu+/N5NBARRDQgRTgjTGCMgHQsE/Q8iAHx5EBm9OkAypb9nS7fHing/muFnAQ73NE="

before_install:
  - mkdir -p $TRAVISCI_SCRIPT_DIR
  - wget https://gist.githubusercontent.com/nolte/33a1a963d8161db0641b59f26d794e01/raw/dockerhub_deploy.sh -O $TRAVISCI_SCRIPT_DIR/dockerhub_deploy.sh
  - chmod u+x $TRAVISCI_SCRIPT_DIR/*

jobs:
  include:
    - stage: build
      script:
        - docker build -t nolte/snapcast-client:$(echo $SNAPCASTVERSION) -f DockerfileClientX86 --build-arg SNAPCASTVERSION=${SNAPCASTVERSION} .
    - script:
        - docker build -t nolte/snapcast-server:$(echo $SNAPCASTVERSION) -f DockerfileServerX86 --build-arg SNAPCASTVERSION=${SNAPCASTVERSION} .
    - script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build -t nolte/rpi-snapcast-client -f DockerfileClientRPI --build-arg SNAPCASTVERSION=${SNAPCASTVERSION} .
      deploy:
        # only executed on master branch
        - provider: script
          script: $TRAVISCI_SCRIPT_DIR/dockerhub_deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD nolte/rpi-snapcast-client rpi-snapcast-client development
          on:
            branch: development
        - provider: script
          script: $TRAVISCI_SCRIPT_DIR/dockerhub_deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD nolte/rpi-snapcast-client rpi-snapcast-client latest
        - provider: script
          script: $TRAVISCI_SCRIPT_DIR/dockerhub_deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD nolte/rpi-snapcast-client rpi-snapcast-client $TRAVIS_TAG
          on:
            tags: true
            all_branches: false

    - script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build -t nolte/rpi-snapcast-server -f DockerfileServerRPI --build-arg SNAPCASTVERSION=${SNAPCASTVERSION} .
      deploy:
        # only executed on master branch
        - provider: script
          script: $TRAVISCI_SCRIPT_DIR/dockerhub_deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD nolte/rpi-snapcast-server rpi-snapcast-server development
          on:
            branch: development
        - provider: script
          script: $TRAVISCI_SCRIPT_DIR/dockerhub_deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD nolte/rpi-snapcast-server rpi-snapcast-server latest
        # Tag deploy all with v started tags to dockerhub (like v0.9-0.11.1)
        - provider: script
          script: $TRAVISCI_SCRIPT_DIR/dockerhub_deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD nolte/rpi-snapcast-server rpi-snapcast-server $TRAVIS_TAG
          on:
            tags: true
            all_branches: false


notifications:
  webhooks: https://keenio-gateway.herokuapp.com/build
  slack:
    rooms:
      secure: wxbdzqs8U7mbB68hNRzVCGEr+NaS2MZu24GdSdvLfV8Pae1vAd4T0fAhi8zzPxvVvQ/AxEDkhmKE9H0FJTkdPl1TqtBc01DGTHzsmMITLCMThBYy0LKgg0UZh4JPg/9svQyut+2mm0u0WImaQ92sK3DfxXQBcPDaLI2LPrffuWiBXjT5tGwu8u9CDYZs5atu1WcsYk4xg0E4s/Y6GMOuDkgLDMECFhrpiHETS+fBBFNNaIpzRhuWO3LVWTy8FjJRiay/V0Hb4ScfzQBfRmDOUqHVhFo1OElUYjsH26Atn75fpPDHr2pZxHWaJZ5naeBQcghTrfoglmzIKmJ1V53ZrtWNhnwWDG0RbtA9ZttRIX9//ip+4ShBoWgn10qacBTlwMidaTDIYG65mL47DR6upCcWl6ex+zX3jnN3W8D9UkM61yRgB8ZcsuIt7G1OB3zirF4+4OuXeMVDjTJExRR7AulBcWTfBPu1CQ9eM3buK0J64DR3jSnXN87Krj6Bhx2mqRKMtc8yWlGLWzwGiZzSj3vOIH/2urYIh+8jkmtrD4mVMLRKma4JyiE/IHya/lzb3082/rMesrmNTZ94pdJB3fU+LWsU0EaGx30/kfJFBru+3HKiEmDZ4Ur9CP3B7XVcdCYZxxHR7F4yy7UZsB0FlQcs7qHYDpPaU+iMUnRzqD4=
    on_success: always
